baseURL = "https://mariuspy.github.io/mi-sitiob/"
languageCode = "es"
title = "Renew Tech"
theme = "tale"
[Author]
    name = "Mario Arzamendia"
[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0

[params]
    css = ["css/estilos.css"]
